### ISSUE TITLE
What happens during a worker node update? 

### ISSUE THREAD

**Issue by emiliamato12** [ibm-cloud-docs/openshift#101]
Hello Team, would be possibile updating the information here https://cloud.ibm.com/docs/openshift?topic=openshift-kubernetes-service-cli#cs_worker_update with more details (a sort of description of "upgrading phases") to explain customers what happens during a worker node update/reboot/reload? 
The main question from a customer is: "during a worker node update, is a worker node reboot/reload part of the process"? 
As far as I know, the behaviour of the update under the covers does something like a reload in that the worker node is reimaged, and data is deleted if not stored outside the worker, but it's not 100% clear if a reload is part of the upgrade process. 
Could you please update the docs with more details about what is done during a worker node update? Thank you.

**Comment by derekpoindexter** [comment]
**The main question from a customer is: "during a worker node update, is a worker node reboot/reload part of the process"?**

Hi, thank you for the feedback. Here is a quick breakdown what happens during each. I've highlighted the key distinctions that I think you are looking for. Let us know if this helps.

[Reboot](https://cloud.ibm.com/docs/openshift?topic=openshift-kubernetes-service-cli#cs_worker_reboot)
> During the reboot, the state of your worker node does not change. For example, you might use a reboot if the worker node status in classic IBM Cloud infrastructure is Powered Off and you need to turn on the worker node. **A reboot clears temporary directories, but does not clear the entire file system or reformat the disks. The worker node IP address remains the same after the reboot operation.**

[Reload](https://cloud.ibm.com/docs/openshift?topic=openshift-kubernetes-service-cli#cs_worker_reload)
> During the reload, your worker node machine is updated with the latest image and data is deleted if not [stored outside the worker node](https://cloud.ibm.com/docs/openshift?topic=openshift-storage_planning#persistent_storage_overview). The worker node public and private IP address remain the same after the reload operation. **Reloading a worker node applies patch version updates to your worker node, but not major or minor updates.**

[Update](https://cloud.ibm.com/docs/openshift?topic=openshift-kubernetes-service-cli#cs_worker_update)
> **Update worker nodes to apply the latest security updates and patches to the operating system, and to update the Kubernetes version to match the version of the Kubernetes master.** You can update the master Kubernetes version with the ibmcloud oc cluster master update [command](https://cloud.ibm.com/docs/openshift?topic=openshift-kubernetes-service-cli#cs_cluster_update). Remember that your worker nodes can be only up to two versions behind the master version (n-2). The worker node IP address remains the same after the update operation.

Some related docs you might find useful.
- [What happens when you update a worker node?](https://cloud.ibm.com/docs/openshift?topic=openshift-update)
- [Worker nodes states here](https://cloud.ibm.com/docs/openshift?topic=openshift-worker-node-state-reference)

**Comment by emiliamato12** [comment]
@derekpoindexter Thank you for your answer. Yes, I'm already aware of the key distinctions you highlighted above, but what I was requesting is to improve the current docs and add more detailed information about what happens at each steps. For example, a worker update include a worker reload/reboot? 
For what I know, **the behaviour of the update under the covers does something like a reload in that the worker node is reimaged, and data is deleted if not stored outside the worker** --> but this is not written in the docs and sometimes customers ask for it. Thank you!
