### ISSUE TITLE
No CRN is attached to the secret stored in Secrets Manager

### ISSUE THREAD

**Issue by lionelmace** [ibm-cloud-docs/openshift#120]
The replacement of Certificate Manager by Secrets Manager requires our documentation to be updated.

In the page [Setting up Ingress](ttps://cloud.ibm.com/docs/openshift?topic=openshift-ingress-roks4), the command below is reference 3 times:
```
ibmcloud oc ingress secret create --cluster <cluster_name_or_ID> --cert-crn <CRN> --name <secret_name> --namespace project
```
Yet, no CRN is returned by the command also referenced on this page
```
ibmcloud oc ingress secret get -c <cluster> --name <secret_name> --namespace openshift-ingress
```
Indeed, a dedicated instance of Secrets Manager attached to the cluster is required to be able to get a CRN.

**Comment by marissa-treible** [comment]
@lionelmace Thank you for opening this issue. Please refer to this page when migrating from Certificate Manager to Secrets Manager. https://cloud.ibm.com/docs/openshift?topic=openshift-certs-mgr-migration#certs-mgr_setup_register

 In these steps, you regenerate your secret so that its CRN references the new Secrets Manager instance. 

<img width="314" alt="image" src="https://user-images.githubusercontent.com/86259088/195661052-60c683d5-af19-4cec-b83d-e184baea4a8b.png">

**Comment by marissa-treible** [comment]
@linonelmace Do you mind sharing the output you get when you run `ibmcloud oc ingress secret get`? This is the output I see after migrating my secrets to Secret Manager.

<img width="1725" alt="get secret output" src="https://user-images.githubusercontent.com/86259088/195662758-05f6b389-0ad0-4ac9-9628-da3bd1d400b3.png">

**Comment by marissa-treible** [comment]
Hi @lionelmace. After reading your comment again, I realize that you are talking about secrets that are not migrated to Secrets Manager at all. I followed up with our dev to confirm that if your secrets are not in Secrets Manager, you must use kubectl commands to manage them.

**Comment by lionelmace** [comment]
@marissa-treible 

To reproduce,
1. Create a new OpenShift cluster v4.11
2. Follow the steps 2 on this page https://cloud.ibm.com/docs/openshift?topic=openshift-ingress-roks4#ingress-roks4-public-2
3. See the output in the screenshot below
<img width="1075" alt="image" src="https://user-images.githubusercontent.com/12241613/196366449-3a5805f5-c27c-4592-97f6-3df93c991d9e.png">

As you can see in the screenshot above, there is no CRN attached to this secret. This is expected as there is no dedicated instance of Secrets Manager attached to the cluster. Thus, the doc is outdated. This was valid for Certificate Manager but not valid any more for Secrets Manager.

**Comment by marissa-treible** [comment]
@lionelmace 

To clarify, these steps are still valid for Secrets Manager if you follow all of the migration steps and set a default Secrets Manager instance, as covered in this migration page https://cloud.ibm.com/docs/openshift?topic=openshift-certs-mgr-migration. When you set the default Secrets Manager instance and regenerate your secrets, they are updated with the CRN of the default Secrets Manager instance. 

However, if you _do not_ migrate your secrets to Secrets Manager and instead have them written directly to your cluster, then the steps in Setting up Ingress do not apply because your secrets will not have a CRN, as covered here https://cloud.ibm.com/docs/openshift?topic=openshift-certs-mgr-migration#certs-mgr_alt. I am working with the Ingress squad to see how we will document this case.

**Comment by marissa-treible** [comment]
This note has been placed throughout the documentation where the secret CRN value is required.

> To create a secret with the `{[icks]} ingress secret create` command, you must have a default [Secrets Manager](/docs/containers?topic=containers-secrets-mgr) instance registered to your cluster. If you do not have a Secrets Manager instance and your secrets are instead written directly to your cluster, your secrets do not have the required CRN value and you must manually copy them with kubectl commands.
