### ISSUE TITLE
Cluster autoscaling is not supported in OCP 3.11

### ISSUE THREAD

**Issue by kissyy** [ibm-cloud-docs/openshift#32]
Cluster autoscaling (worker node autoscaling) is not supported in OCP 3.11 (k8s 1.11) because it requires k8s 1.12.

https://cloud.ibm.com/docs/openshift?topic=openshift-ca

**Comment by artberger** [comment]
@kissyy thanks for your feedback. In the [cluster autoscaler installation docs](https://cloud.ibm.com/docs/openshift?topic=openshift-ca#ca_helm), we tell the users to install Helm Tiller 2.12 so that the autoscaler can still be supported. Are you experiencing any issues with this? If so, let us know, in the [internal](https://ibm-argonauts.slack.com/archives/C90D3KZUL) or [external](https://ibm-container-service.slack.com/archives/CF6APMLBB) Slack.
