### ISSUE TITLE
Please notify when new IP addition into OC firewall

### ISSUE THREAD

**Issue by mkmrah** [ibm-cloud-docs/openshift#36]
Hi, We from IBM cloud schematics service (Orchestrator as service in IBM cloud) team and our service used by Cloudpak customers to deploy the coudpak into their ROKS

From our service we whitelist only this (`https://github.com/ibm-cloud-docs/openshift/blob/master/openshift_firewall.md.`) IP ranges to meet security guidelines. we want to get notified before this list updated to avoid cloudpak deployment failures. 

we also look at this document manually every week to catch the new addition IPs but still this is not efficient as the doc update happen any point in time. 

So here is the summary

* We are not able to keep-up.   Customers are complaining; and we are reactive..
We would like to be proactive.. 
* Is it possible to get notified about the new IP ranges that we must whitelist in our deployments - to ensure that the CloudPaks can be deployed in those target clusters.

**Comment by artberger** [comment]
Hi @mkmrah thanks for your feedback on the firewall documentation. You are right that at this time, the docs, and probably [this release notes page](https://cloud.ibm.com/docs/openshift?topic=openshift-iks-release), are the best way to keep up with the changing IP addresses. I will add this to some of our internal issues about improving the notification experience for users. Also, since you're an IBMer, feel free to continue the conversation in our [internal slack channel](https://ibm-argonauts.slack.com/archives/CJH0UPN2D). There might be some issues you could follow that I'm not aware of.
