### ISSUE TITLE
4.3 is available since 20 April 2019?

### ISSUE THREAD

**Issue by flyingbarron** [ibm-cloud-docs/openshift#37]
2019 instead of 2020 in the release notes on April 21
https://cloud.ibm.com/docs/openshift?topic=openshift-iks-release

**Comment by artberger** [comment]
@flyingbarron thank you for raising this issue. Yes, the year should have been 2020. Unfortunately I cannot merge in your PR because of our doc builds, but I have made this update in our source repo.
![image](https://user-images.githubusercontent.com/20074219/80416703-925efe80-88a2-11ea-97c4-6df406de5527.png)
