### ISSUE TITLE
Attempt to expose deployment/hello-world ... results in Error ("hello-world" not found)

### ISSUE THREAD

**Issue by itl-wengng** [ibm-cloud-docs/openshift#51]
Hello All - beginner in the world of VPC and clusters - need help

I am working thru Tutorial "Creating an OpenShift cluster in your Virtual Private Cloud (VPC)"
In Step 3: Setting up a VPC load balancer to expose your app publicly

I type in the following command - which results in error. Can anyone help & see what I may have done wrong?

 oc expose deployment/hello-world --type=LoadBalancer --name=hw-lb-svc  --port=8080 --target-port=8080
Error from server (NotFound): deployments.apps "hello-world" not found

It seems like my previous steps have been successful

weng_ng@cloudshell:~$ oc get svc -n hello-world
NAME          TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
hello-world   ClusterIP   172.21.135.21   <none>        8080/TCP   96m
weng_ng@cloudshell:~$ 

weng_ng@cloudshell:~$ oc get pods -n hello-world
NAME                   READY   STATUS      RESTARTS   AGE
hello-world-1-build    0/1     Completed   0          97m
hello-world-1-deploy   0/1     Completed   0          96m
hello-world-1-dhcmc    1/1     Running     0          96m

**Comment by Rachael-Graham** [comment]
Hello - looks like that command doesnt have the project in it! I will update the doc so that the command should be: `oc expose deployment/hello-world --type=LoadBalancer --name=hw-lb-svc --port=8080 --target-port=8080 -n hello-world`. And the command in the next step should include the project too: `oc describe service hw-lb-svc -n hello-world`

Doc changes will go out today. Re-open if specifying the project in those commands doesn't reslve the issue for you!

**Comment by itl-wengng** [comment]
Rachel - thank you.
I talked with IBM Support and they also found another issue - that they have opened a ticket for.
This tutorial instructs to expose the deployment of the hello-world app.
But the prior steps never creates the deployment. Instead the steps create a deployment config.
This is why the expose deployment line fails.

Link to tutorial is:   (https://cloud.ibm.com/docs/openshift?topic=openshift-vpc_rh_tutorial)

Hope this info is helpful to you. Thanks for all you do.
