### ISSUE TITLE
--provider <vpc-gen2> is not supprted in ibmcloud oc cluster create

### ISSUE THREAD

**Issue by teruz** [ibm-cloud-docs/openshift#59]
The doc shows "--provider <vpc-gen2>" in ibmcloud oc cluster create but if specified it results in error.

> Incorrect Usage: flag provided but not defined: -provider

I tested in OpenShift 4.5 on VPC Gen2.

**Comment by artberger** [comment]
@teruz , yes that is correct, to create a cluster, you put the provider after the command name, like `ibmcloud oc cluster create vpc-gen2` or `ibmcloud oc cluster create vpc-classic`. I have gone through our source doc and removed the `--provider` flag in a couple places, mostly on the cluster create page. If there were a specific doc you were looking at, I can also check that. The changes will go out in the next prod push, so I am going to close this issue here. Thanks again for your feedback!
