### ISSUE TITLE
--workers is not optional

### ISSUE THREAD

**Issue by hidekazuna** [ibm-cloud-docs/openshift#68]
To create a VPC cluster from the CLI, `--workers` parameter is not optional actually.

```sh
$ ibmcloud oc cluster create vpc-gen2 --name mycluster --zone jp-tok-1 --vpc-id $vpc --subnet-id $subnet --flavor bx2.4x16 --version 4.6_openshift --cos-instance $crn

Creating cluster...
FAILED
The requested number of worker nodes is fewer than the minimum 2 worker nodes that are required for an OpenShift cluster. You have 0 existing worker nodes in the cluster, which you requested to change by 1 worker nodes. Revise your request, and try again. (E3310)
```

Document URL:
https://cloud.ibm.com/docs/openshift?topic=openshift-clusters&locale=en#cluster_vpcg2_cli

**Comment by artberger** [comment]
@hidekazuna thanks for raising this issue. I am checking with the development team and will let you know if I find anything and update the doc either way.

**Comment by artberger** [comment]
An update: So for Kubernetes clusters, the `--workers` flag is optional because it defaults to 1 worker. However, for OpenShift clusters, the minimum number of required worker nodes is 2, so the default of 1 is not sufficient and hence the command fails as you noted. So the `--workers` flag is required for OpenShift clusters. I updated the doc and the change will go out with the next prod push. I'm going to close this here; thanks again for opening the issue.
