### ISSUE TITLE
ACL rule source/destination ports flipped?

### ISSUE THREAD

**Issue by wdapalma** [ibm-cloud-docs/openshift#71]
In the "Controlling traffic with ACLs" section:

Step 5, inbound rules has:

- Allow incoming traffic requests to apps that run on your worker nodes
- Source IP: any
- Source Port: 30000-32767
- Destination IP: any
- Destination Port: any

and in Step 6, its "counterpart" outbound rule has: 
- Source IP: any
- Source Port: 30000-32767
- Destination IP: any
- Destination Port: any

But, as it is written, the are the same, in different directions, so one of them is flipped.
Based on the description, it seems the inbound rule should be:
- **Destination Port: 30000-32767**

**Comment by Rachael-Graham** [comment]
The [console steps](https://cloud.ibm.com/docs/containers?topic=containers-vpc-network-policy#acls_ui) and [CLI steps](https://cloud.ibm.com/docs/containers?topic=containers-vpc-network-policy#acls_cli) have been updated. In particular I believe you're right, the directionality of the ports was incorrect, so that has been updated. I will close this issue, but please re-open if you are still having issues or have other questions!
